// 现代合成旅动态编组系统 v0.1.4
// 目标：兼容现有历史战役引擎；红/蓝仅为现代演习显示语义，底层继续使用 chinese/japanese。
// 编制与装备数量均为游戏化抽象，不代表现实部队精确编制。

const EQUIPMENT = {
  ZTZ99A:{name:"ZTZ-99A主战坦克"}, ZBD04A:{name:"ZBD-04A步兵战车"}, PLZ05:{name:"PLZ-05自行榴弹炮"},
  HQ17A:{name:"红旗-17A野战防空系统"}, ZTL11:{name:"ZTL-11轮式突击车"}, ZBL08:{name:"ZBL-08轮式步兵战车"},
  PCL181:{name:"PCL-181车载榴弹炮"}, CSK181:{name:"CSK-181装甲高机动车"}, PCP001:{name:"轻型火力支援车"},
  UAV_RECON:{name:"战术侦察无人机系统"}, ENG_VEH:{name:"装甲工程保障车辆"}, LOG_VEH:{name:"综合保障车辆"}
};

const TEMPLATES = {
  heavy:{name:"重型合成旅",maneuver:"heavy",tank:"ZTZ99A",ifv:"ZBD04A",art:"PLZ05",ad:"HQ17A",support:"ZBD04A",atk:1.12,def:1.15,mov:.92},
  medium:{name:"中型合成旅",maneuver:"medium",tank:"ZTL11",ifv:"ZBL08",art:"PCL181",ad:"HQ17A",support:"ZBL08",atk:1.02,def:.98,mov:1.16},
  light:{name:"轻型合成旅",maneuver:"light",tank:"CSK181",ifv:"CSK181",art:"PCL181",ad:"HQ17A",support:"PCP001",atk:.90,def:.86,mov:1.25}
};

const eqName = id => EQUIPMENT[id]?.name ?? id;

function make(id,name,faction,type,echelon,q,r,strength,attack,defense,movement,range,equipment,qty,formation,parentHQ=null){
  return {
    id, name:`${name}｜${eqName(equipment)}`, fullName:name,
    faction,type,echelon,q,r,strength,maxStrength:strength,manpower:strength,maxManpower:strength,
    attack,defense,movement,movementPoints:movement,maxMovementPoints:movement,
    actionPoints:4,maxActionPoints:4,range,morale:82,ammo:100,fuel:100,supply:100,
    formation,parentHQ,
    // 让主系统明确知道这是动态生成单位；后续发生“同格冲突”时允许安全系统自动调整。
    autoGenerated:true,
    equipment:[{type:equipment,name:eqName(equipment),initial:qty,operational:qty,damaged:0,destroyed:0}],
    equipmentSummary:`${eqName(equipment)} ${qty}/${qty}`,
    modern:{c2:100,intelLevel:0,supply:100,ammo:100,fuel:100,parentHQ,exerciseSide:faction==="chinese"?"RED":"BLUE"}
  };
}

function maneuverCompanies(T,side,b,faction,slots,form,bnHQ){
  const p=`${side}_BN${b}`, a=[];
  const add=(suffix,name,type,eq,qty,atk,def,mov,slotIndex)=>{
    const x=slots[slotIndex];
    a.push(make(`${p}_${suffix}`,name,faction,type,"company",x.q,x.r,100,
      Math.round(atk*T.atk),Math.round(def*T.def),Math.max(4,Math.round(mov*T.mov)),type==="tank"?2:1,eq,qty,form,bnHQ));
  };
  if(T.maneuver==="heavy"){
    add("T1",`第${b}合成营坦克1连`,"tank",T.tank,14,12,10,5,0);
    add("T2",`第${b}合成营坦克2连`,"tank",T.tank,14,12,10,5,1);
    add("M1",`第${b}合成营装甲步兵1连`,"infantry",T.ifv,14,9,9,5,2);
    add("M2",`第${b}合成营装甲步兵2连`,"infantry",T.ifv,14,9,9,5,3);
  } else if(T.maneuver==="medium"){
    add("A1",`第${b}合成营轮式突击连`,"tank",T.tank,14,10,8,6,0);
    add("M1",`第${b}合成营轮式装步1连`,"infantry",T.ifv,14,9,8,6,1);
    add("M2",`第${b}合成营轮式装步2连`,"infantry",T.ifv,14,9,8,6,2);
    add("M3",`第${b}合成营轮式装步3连`,"infantry",T.ifv,14,9,8,6,3);
  } else {
    for(let i=0;i<4;i++) add(`L${i+1}`,`第${b}合成营高机动步兵${i+1}连`,"infantry",T.ifv,18,8,7,7,i);
  }
  const s=slots[4];
  a.push(make(`${p}_SUP`,`第${b}合成营支援保障连`,faction,"support","company",s.q,s.r,90,4,6,5,2,T.support,10,form,bnHQ));
  return a;
}

// 固定安全部署表：刻意避开 q=29/30 河道以及桥头目标格。
// 红方西侧、蓝方东侧；1/2营为第一梯队，3/4营为第二梯队。
const DEPLOYMENT = {
  RED:{
    hq:{q:6,r:20}, art1:{q:8,r:13}, art2:{q:8,r:27}, ad:{q:7,r:17}, recon:{q:20,r:20}, eng:{q:9,r:22}, log:{q:5,r:24},
    battalions:[
      {hq:{q:13,r:8},  c:[{q:15,r:7},{q:17,r:7},{q:15,r:9},{q:17,r:9},{q:13,r:10}]},
      {hq:{q:13,r:16}, c:[{q:15,r:15},{q:17,r:15},{q:15,r:17},{q:17,r:17},{q:13,r:18}]},
      {hq:{q:9,r:25},  c:[{q:11,r:24},{q:13,r:24},{q:11,r:26},{q:13,r:26},{q:9,r:27}]},
      {hq:{q:9,r:33},  c:[{q:11,r:32},{q:13,r:32},{q:11,r:34},{q:13,r:34},{q:9,r:35}]}
    ]
  },
  BLUE:{
    hq:{q:53,r:20}, art1:{q:51,r:13}, art2:{q:51,r:27}, ad:{q:52,r:17}, recon:{q:39,r:20}, eng:{q:50,r:22}, log:{q:54,r:24},
    battalions:[
      {hq:{q:46,r:8},  c:[{q:44,r:7},{q:42,r:7},{q:44,r:9},{q:42,r:9},{q:46,r:10}]},
      {hq:{q:46,r:16}, c:[{q:44,r:15},{q:42,r:15},{q:44,r:17},{q:42,r:17},{q:46,r:18}]},
      {hq:{q:50,r:25}, c:[{q:48,r:24},{q:46,r:24},{q:48,r:26},{q:46,r:26},{q:50,r:27}]},
      {hq:{q:50,r:33}, c:[{q:48,r:32},{q:46,r:32},{q:48,r:34},{q:46,r:34},{q:50,r:35}]}
    ]
  }
};

function brigade(side,type){
  const T=TEMPLATES[type]??TEMPLATES.heavy;
  const faction=side==="RED"?"chinese":"japanese";
  const D=DEPLOYMENT[side], arr=[], bdeHQ=`${side}_BDE_HQ`;
  arr.push(make(bdeHQ,`${side==="RED"?"红方":"蓝方"}${T.name}旅指挥所`,faction,"headquarters","brigade",D.hq.q,D.hq.r,320,3,12,3,1,"LOG_VEH",8,T.name,null));
  D.battalions.forEach((P,i)=>{
    const b=i+1, bnHQ=`${side}_BN${b}_HQ`, form=`${T.name}·第${b}合成营`;
    arr.push(make(bnHQ,`第${b}合成营指挥所`,faction,"headquarters","battalion",P.hq.q,P.hq.r,180,3,9,4,1,"LOG_VEH",4,form,bdeHQ));
    arr.push(...maneuverCompanies(T,side,b,faction,P.c,form,bnHQ));
  });
  arr.push(make(`${side}_ART1`,"旅炮兵营第1火力连",faction,"artillery","company",D.art1.q,D.art1.r,120,13,5,4,6,T.art,6,T.name,bdeHQ));
  arr.push(make(`${side}_ART2`,"旅炮兵营第2火力连",faction,"artillery","company",D.art2.q,D.art2.r,120,13,5,4,6,T.art,6,T.name,bdeHQ));
  arr.push(make(`${side}_AD`,"旅防空营野战防空连",faction,"air_defense","company",D.ad.q,D.ad.r,110,7,7,4,4,T.ad,6,T.name,bdeHQ));
  arr.push(make(`${side}_RECON`,"旅侦察营无人侦察连",faction,"recon","company",D.recon.q,D.recon.r,90,4,5,7,4,"UAV_RECON",6,T.name,bdeHQ));
  arr.push(make(`${side}_ENG`,"旅作战支援营工程连",faction,"engineer","company",D.eng.q,D.eng.r,100,5,7,4,1,"ENG_VEH",10,T.name,bdeHQ));
  arr.push(make(`${side}_LOG`,"旅勤务保障营保障连",faction,"supply","company",D.log.q,D.log.r,100,2,6,4,1,"LOG_VEH",18,T.name,bdeHQ));
  return arr;
}

export class ModernBrigadeSystem {
  static isModern(config){return config?.modernBrigadeSelection===true;}
  static getSelection(){try{return JSON.parse(sessionStorage.getItem("modernBrigadeSelection")||"{}");}catch{return {};}}
  static generate(config){
    const s=this.getSelection();
    const units=[...brigade("RED",s.red||"heavy"),...brigade("BLUE",s.blue||"medium")];
    // 最后一层内部自检：任何单位都不得落入预留河道列。
    for(const u of units){
      if(u.q===29||u.q===30) console.error("[现代旅编组] 单位落入河道预留列",u.id,u.q,u.r);
    }
    return units;
  }
  static templateInfo(){return TEMPLATES;}
}
